### ISSUE TITLE
OS X Mavericks failed build with clang

### ISSUE THREAD

**Issue by max91219** [TRIQS/triqs#228]
Hi,

I have just tried to build triqs on my macbook pro running OS X Mavericks using clang. I have installed all the librarys and dependencies using the guide on your website and as far as I can tell they have all been subsequently picked up by CMake (See attached Gist). However, when i come to run make clang reports an error while building pytriqs/operators/operators_wrap.cpp the error is the following

In file included from /Users/maxhowell/triqs/build/pytriqs/operators/operators_wrap.cpp:7:
/Users/maxhowell/triqs/src/triqs/python_tools/converters/vector.hpp:11:14: error: implicit instantiation of undefined template
      'triqs::py_tools::py_converter<boost::variant<int, std::__1::basic_string<char> > >'
   pyref y = py_converter<T>::c2py(x);

full output of the cmake and make commands can be found in the following gist along with my CMakeCache.txt file

https://gist.github.com/max91219/9bf72bf8be83cba4cd36

thanks in advanced for your help

max

**Comment by krivenko** [comment]
Hi Max,
Could you show us the auto-generated wrapper (`/Users/maxhowell/triqs/build/pytriqs/operators/operators_wrap.cpp`)?
Cheers,
Igor

**Comment by max91219** [comment]
Hi Igor,

here is the contents of the file, https://gist.github.com/max91219/d4f40faf9fdef3ab7047

thanks again,

Max

**Comment by parcollet** [comment]
Hi, 

Thanks for the report and sorry for the long delay in answering...

The issue comes from a change in boost. 
boost 1.58 is the new default in brew (as usual, it has changed without warnings, without us even knowing about it ...)
I upgraded to 1.58 on my mac, and I have the same issue.

More specifically : 

In file included from /.../triqs/BUILD/triqs/pytriqs/operators/operators_wrap.cpp:8:
..../triqs/src/triqs/triqs/python_tools/converters/variant.hpp:18:36: warning: class template partial specialization contains a template parameter that can not be deduced; this partial specialization will never be used
template<typename... Types> struct py_converter<boost::variant<Types...>> {
                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/parcolle/triqs/src/triqs/triqs/python_tools/converters/variant.hpp:18:22: note: non-deducible template parameter 'Types'
template<typename... Types> struct py_converter<boost::variant<Types...>> {
                     ^
then same as issue....

1- something clearly has changed in boost 1.58, which break our codes.
2- I do not see what now.
3- I think the best here would be to write a simple variant by hand (I have it) and get rid of this boost::variant anyway... Too complex, now it breaks code causing issues...
@mferrero, @krivenko: opinions ?

**Comment by parcollet** [comment]
@krivenko : same issue in #207

**Comment by krivenko** [comment]
@parcollet
O.k., I don't mind throwing away `boost::variant` in favor of a simpler homemade solution. Still, I would keep some degree of generality. If you don't want to go for a fully variadic union with an arbitrary number of stored types, we could use, say, only two adjustable types.

But would it be much more difficult to write the variadic thing? I shall take care of the Python converter anyway.

**Comment by krivenko** [comment]
@parcollet Please, answer to my comment before you merge the change.

Removing `boost::variant` will break my code, and who knows how much code of other users of the library. The new implementation you propose in 18b62dea47312c2f7bf7d2b08b9c516a0066fc1e has no generality at all, a string/int pair is fixed with nails there. This means people will have to basically copy and paste your ` triqs/utility/variant_int_string.hpp` and ` triqs/python_tools/converters/variant_int_string.hpp `, change the types (or add some more), and do so for every application they write. Waste of time + source of new bugs.

And this is a very general problem of TRIQS as a library, going far beyond the issue we are discussing now. In my opinion, features should not be removed without providing an adequate substitute. Once a feature has been introduced in a major release (1.0/1.1/1.2/...), it should be considered to be used by someone. If in a later release the feature disappears or becomes much less usable, people are likely to stop using new lib versions (I remember you met with this practice before).

**Comment by parcollet** [comment]
1- Indeed, the branch variant_fix is there for discussing before merging...
2- The point here is that boost::variant is simply broken in later releases. 
It does not compile any more our code, and lead to complicated issues for users. 
We need to fix this a.s.a.p.
3- The replacement is quite simple, and does what we need for our public codes.
4- Generally speaking, the only features that we guarantee to keep are the *documented ones*, in the doc. We do not break them, unless rarely if there is a really very serious reason to do it.
The rest is alpha, or implementation details and it can change.
Otherwise, any alpha code will be frozen immediately.
5- However, there is indeed not need to remove the previous variant code from converters if you need it.
