### ISSUE TITLE
Changelog absent for change to complex g(tau)

### ISSUE THREAD

**Issue by Titan-C** [TRIQS/triqs#280]
I just compiled from master and noticed that plots of Matsubara Green's Functions show also the negative frequencies part. Why? and why is it not in the change log?
But I also notice that the data attribute also presents the array in the negative frequencies but when saving to a file only the positive frequencies are stored.
How can I recover the old behavior? I worked around it with the function call that returns the value for each frequency, but it does not take arrays so I have to wrap it in a list comprehension. And slicing the data attribute on the required frequencies becomes complicated as I would have to keep track of the size.

**Comment by parcollet** [comment]
Because we forgot to push the changelog in master ...
We also still need to update the doc of GF for this. 

There is a major change in master, i.e. using by default complex g(tau), which requires 
storing negative frequencies for g(omega).
It was necessary to do it, even though it is a small API break, for e.g. for computation with spin orbits, 
and more generally in the realistic context where having only positive frequencies can be error prone.

In Python, you can not get the old behaviour. 
It was decided that it would be too confusing.

When saving in file, if the g(omega) has the proper symmetry, we save only the om> 0 part to save space.

Your specific question about data:
What exactly do you want to do ? Why do you work with data and not with the function call ?
What do you mean by "it does not take arrays so I have to wrap it in a list comprehension." ?

**Comment by Titan-C** [comment]
>It was necessary to do it, even though it is a small API break, for e.g. for computation with spin orbits,
>and more generally in the realistic context where having only positive frequencies can be error prone.

nice

> What exactly do you want to do ? Why do you work with data and not with the function call ?
> What do you mean by "it does not take arrays so I have to wrap it in a list comprehension." ?

I'm keeping track of the first frequencies, by slicing the array
what I use to do: 
```python
f_iw = gf_iw.data[:n_freq]
```
what I do now:

```python
f_iw = [gf_iw(i) for i in range(n_freq)]
```
if would be nice to have a vectorized form that takes
```python
f_iw = gf_iw(range(n_freq))
```

**Comment by aichhorn** [comment]
You can also calculate the index of the first positive Matsubaras and use the gf_iw.data. But I don't see the problem with your solution. Sure, it creates computational overhead, but so what?

**Comment by parcollet** [comment]
f_iw = gf_iw.data[ len(gf.mesh)/2 : n_freq ]

**Comment by mferrero** [comment]
I updated the changelog in e12c61a. I don't think it is a good idea to add an overload to the (), Olivier's option seems clear and clean to me.
