### ISSUE TITLE
Initialize/assign Semicircular green's function in c++

### ISSUE THREAD

**Issue by henhans** [TRIQS/triqs#310]
Dear TRIQS team,

I'm wondering if there's an easy way to assign/initialize a semicircular GF in C++ using clef placeholder. The way I was thinking is using the auto assign as

```
auto g1 = gf<imfreq>{{beta, Fermion, Nfreq}, {1, 1}};
triqs::clef::placeholder<0> wn_;
g1(wn_) << 2. * ( wn_ - 1_j * sgn(imag(wn_)) * sqrt( D*D + imag(wn_)*imag(wn_) ) )
```

However, the compilation shows a lot of error complaining about "invalid use of void expression"  and "no matching function for call to ‘sqrt(triqs::gfs::tail)’ "....

I found a way to do it using for loop

```
for(const auto & om: g1.mesh()) {
  std::complex<double> tmp_om = std::complex<double>(om) ;
  g1[om](0,0) = 2. * ( tmp_om - 1_j * sgn(imag(tmp_om)) * sqrt( D*D + imag(tmp_om)*imag(tmp_om) ) );
  std::cout << tmp_om << "\t" << g1[om](0,0) << std::endl;
}
```

Then, fit the GF tail. But I'm wondering if there's a better way to do it?

Thank you!
Tsung-Han

**Comment by parcollet** [comment]
Hi, 
no there is not, simply because the computation of the tail is only possible in simple cases, like 
fractions. The C++ compiler can not handle a more complex formal calculation (expanding at large omega).
The error message will however soon be improved (I have a patch for that).
Your current solution is correct.

**Comment by parcollet** [comment]
@mferrero : what about the proposed change for tail behaviour ?
If this case, the tail would silently be unmodified by the expression ....
