### ISSUE TITLE
How to measure operator averages

### ISSUE THREAD

**Issue by CripleH** [TRIQS/triqs#358]
Hi!

I have question regarding how to measurements. For example, I want to measure the S2 operator.  Let's say I define the operator as:
`S2=S2_op(['up','down'], [0,1,2], {('up', 0): ('up_0', 0), ('down', 0): ('down_0',0)}  )`
Following the manual page 
https://triqs.ipht.cnrs.fr/1.4/applications/cthyb/reference/observables.html
 I then set `measure_density_matrix`to `True`
How do I make TRiQS do the actual averaging <O> = Tr (O*rho) ?
I need to feed it into the solver object, S=solve( ... ) somehow.

I suppose I could also access the density matrix and print it, and then calculate the trace by hand. But then I would really appreciate some python help how to print it in an understandable format.

All the best,
Marcus

**Comment by krivenko** [comment]
Hi Marcus,

You should take a look at `test/python/measure_static.py` in the sources of `cthyb`. It shall answer most of your questions.

>  How do I make TRiQS do the actual averaging <O> = Tr (O*rho) ?

There is a function called `trace_rho_op()`. It does exactly what you need.

> I suppose I could also access the density matrix and print it, and then calculate the trace by hand. But then I would really appreciate some python help how to print it in an understandable format.

The density matrix is accessible via `S.density_matrix`. It is represented as a list of 2-dimensional NumPy arrays, one list element per diagonal block of the density matrix (or, equivalently, of the local Hamiltonian).

P.S. The correct issue tracker for your question is [here](https://github.com/TRIQS/cthyb/issues), since it's about the *cthyb* solver. Please, pay attention to this difference next time you report an issue.

Regards,
Igor

**Comment by krivenko** [comment]
It makes sense to transform `measure_static.py` into a new user guide page.
Assigning myself...

**Comment by CripleH** [comment]
Thank you for a quick response!

**Comment by krivenko** [comment]
New guide about static observables is added in TRIQS/cthyb@ddfadf545f44f2d40cc4a249153b750b928d9a8c. Closing.
