### ISSUE TITLE
HDF5 tests fail

### ISSUE THREAD

**Issue by Atomtomate** [TRIQS/triqs#380]
this is #353 ( as i can not reopen that issue)

for me the h5py tests still fail on arch linux and Ubuntu 16.04.2 LTS
[LastTest.txt](https://github.com/TRIQS/triqs/files/790050/LastTest.txt)

e.g.  ctest -V -R gf_init
`169: Test command: /usr/bin/cmake "-Dname=gf_init" "-Dcmd=[PATH]/triqs.build/build_pytriqs" "-Dinput=[PATH]/triqs.src/test/pytriqs/base/gf_init.py" "-P" "[PATH]/triqs/triqs.build/Config/run_test.cmake"
169: Test timeout computed to be: 9.99988e+06
169: Command for the test: [PATH]/triqs/triqs.build/build_pytriqs [PATH]/triqs.src/test/pytriqs/base/gf_init.py
169: CMake Error at [PATH]/triqs.build/Config/run_test.cmake:37 (message):
169:   Error runing test 'gf_init': ; command:
169:   [PATH]/triqs/triqs.build/build_pytriqs; shell output: 1!
169: 
169: 
1/1 Test #169: gf_init ..........................***Failed    0.18 sec`

>>> h5py.version.version
'2.6.0'
>>> h5py.version.hdf5_version
'1.8.16'
>>> h5py.version.api_version
'1.8'

on arch linux i tried this with hdf5 versions: 1.10.0, 1.8.17, 1.8.4 (compilation of h5py, 1.10 for triqs) and still came up with this error.

**Comment by HugoStrand** [comment]
I am not sure what the problem is, could you check the output of the `gf_init` test? The standard error and standard output from the script is in your cmake build directory under `./test/pytriqs/base/gf_init.err` and `./test/pytriqs/base/gf_init.out`.

Please also look at issue #393 for pointers on how to check what `hdf5` libraries are used in the linking, just note that on linux you have to replace `otool -L` with `ldd`.

**Comment by Wentzell** [comment]
@Atomtomate  Did you solve the problem?

**Comment by parcollet** [comment]
Closed due to inactivity. Reopen if needed.
Not reproduced.
