### ISSUE TITLE
Mac: Unknown CMake command "EXEC_PYTHON_SCRIPT" with PythonSupport=OFF in 1.0 and 1.1.0

### ISSUE THREAD

**Issue by aeantipov** [TRIQS/triqs#40]
**On a mac**. During configuration TRIQSConfig.cmake is patched via a python script invoked via a macro EXEC_PYTHON_SCRIPT. However if PythonSupport is set to OFF, this macro is left unknown to the installation, so the error is raised. Since python is shipped with mac os in any case, the `find_package(Python)` can be used safely just before this invocation.
So, this works

<pre>
diff --git CMakeLists.txt CMakeLists.txt
index eba818a..cfbeaee 100644
--- CMakeLists.txt
+++ CMakeLists.txt
@@ -398,6 +398,7 @@ if(NOT ${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
  configure_file(./cmake/TRIQSConfig.cmake.in Config/TRIQSConfig.cmake @ONLY)
 else()
  configure_file(./cmake/TRIQSConfig.cmake.in Config/TRIQSConfig1.cmake @ONLY )
+ find_package(Python)
  EXEC_PYTHON_SCRIPT( "import re;open('${CMAKE_CURRENT_BINARY_DIR}/Config/TRIQSConfig.cmake','w').write(re.sub(r';*\\s*-framework\\s+([a-zA-Z_][a-zA-Z_0-9]*)',r' \"-framework \\1\"',open('${CMAKE_CURRENT_BINARY_DIR}/Config/TRIQSConfig1.cmake').read()))", ConfigFile)
 endif()
 </pre>

This applies to both master and 1.1.0_new branches

**Comment by patrikthunstrom** [comment]
This is not a proper fix since it only works if mako is installed, which it is not by default. See the following output:


-- -------- Python detection -------------
-- Python interpreter /usr/bin/python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named mako.template
CMake Error at cmake/FindPython.cmake:43 (MESSAGE):
  The script : import mako.template

   did not run properly in the Python interpreter. Check your python installation.
Call Stack (most recent call first):
  cmake/FindPython.cmake:57 (EXEC_PYTHON_SCRIPT)
  CMakeLists.txt:546 (find_package)


-- Configuring incomplete, errors occurred!

**Comment by patrikthunstrom** [comment]
The least dirty fix of the fix I could find is to put a "if (PythonSupport)" right after "ENDFUNCTION (EXEC_PYTHON_SCRIPT)" in FindPython.cmake, and then close the if statement in the very end of the file, just after "set (PYTHONLIBS_FOUND TRUE) #${PYTHON_FOUND})".
