### ISSUE TITLE
Add 'oplotr' as an attribute to the 'AxesSubplot' object in pytriqs version of matplotlib [unstable]

### ISSUE THREAD

**Issue by amoutenet** [TRIQS/triqs#477]
Hi all,

I am used to handle subplots in my pytriqs notebook in the following way:

`from pytriqs.gf import *`
`from pytriqs.plot.mpl_interface import *`
`%matplotlib inline`

`G=GfImTime(indices=[0], beta=100, n_points=100)`
`f, (ax1, ax2) = plt.subplots(2)`
`ax1.oplot(G.real)`
`ax2.oplotr(G)`

The point here is that the ax1.oplot() command is working well, but not the ax2.oplotr() one, which gives the following error message: " 'AxesSubplot' object has no attribute 'oplotr' ".

Cheers,

Alice

**Comment by tayral** [comment]
I don't know if this helps, but another way to plot the real part is to write
```python
oplot(G, mode = 'R') # and 'I' for imaginary
```
Cheers
Thomas

**Comment by parcollet** [comment]
@mferrero @Wentzell 
mode should be deprecated, G.real is the proper way with the new gf, it is very natural.
Assigned to me

**Comment by mferrero** [comment]
OK fair enough. What about `oploti` and `oplotr`? Also deprecated?

**Comment by tayral** [comment]
I would also vote for oploti/oplotr to become deprecated (very un-python like and unusual)
PS: after couple of months of usage, mode = "R" is actually quite useful  to do plots like:
```python
for comp in ["R", "I"]:
  oplot(G, mode = comp)
```
(However the name 'mode' is quite awkward, I would call it "comp = 'R'" for component...  because 'mode' could be used for different plotting modes for functions of k, see https://triqs.ipht.cnrs.fr/1.x/tutorials/gfs/lattice_gfs_tutorial_python.html where I gave some examples... but had to go around 'mode'...)
Of course, one can play a similar game with G.real and .imag
```python
for f in [lambda x:x.real, lambda x:x.imag]:
  oplot(f(G))
```
but it looks a bit kludgy, doesn't it?
Thomas

**Comment by krivenko** [comment]
>  PS: after couple of months of usage, mode = "R" is actually quite useful to do plots like:
> ```python
> for comp in ["R", "I"]:
>   oplot(G, mode = comp)
> ```

As a side note, you can achieve a similar result with
```python
for p in [oplotr, oploti]: p(G)
```

**Comment by Wentzell** [comment]
Both `oploti` and `oplotr` are deprecated and will be removed in a future release.
