### ISSUE TITLE
def write_gf_to_txt writes 0 instead of w

### ISSUE THREAD

**Issue by leopo** [TRIQS/triqs#565]
The function def write_gf_to_txt from pytriqs.gf.tools does not write correctly the gf blocks to text file. 0 is put instead of frequencies, so that output looks like that

> 0.000000000000000000e+00 2.342852687337616271e-04 1.242301961304071410e-02
> 0.000000000000000000e+00 2.347431260515794784e-04 1.243514787934770459e-02
> 0.000000000000000000e+00 2.352023266741857513e-04 1.244729984048334112e-02
> 0.000000000000000000e+00 2.356628758608514916e-04 1.245947556592649601e-02
> 0.000000000000000000e+00 2.361247788966151925e-04 1.247167512542779466e-02
> ...  

the GF values look OK

The call is 

> from pytriqs.gf.tools import  *
> write_gf_to_txt(S.G0_iw['ud'])

S.G0_iw['ud'] is a 2x2 GF block

**Comment by mzingl** [comment]
Yes, this is a bug on unstable.
Line 211 in tools.py should be replaced with:
`mesh = np.array([w.real for w in g.mesh]).reshape(-1,1)`
and line 213 with:
`mesh = np.array([w.imag for w in g.mesh]).reshape(-1,1)`

Can someone with push rights fix this bug?

There is clearly a test missing for these read/write functions in tools.py!
We have one in dft_tools, but weirdly we don't make use of write_gf_to_txt, but
only of the read_gf_from_txt function. After this bug is fixed I'll update dft_tools.

I know it is not popular with many, but I would strongly vote for functions to read/write all type of
Gfs to/from files. 

Best,
Manuel

**Comment by parcollet** [comment]
Fixed the file.  cc @Wentzell 
Indeed, we would need a test.

We have a way to read/write all Gf to files, in HDF5, which is our primary file format.

One has to distinguish two things : 

- read/write function to disk in some text format to save them and retrieve them.

- write some text file to send it to a plotting tool which does not support hdf5,
  i.e. basically a non python/matplotlib/jupyter tool. 
  This means writes the text in a precise form lines/cols
  corresponding to the input of the tool, maybe some header, which can be tool specific. 
  It is an interface question.
  Then why do we need to read back ?

Doing the first task with text files would be quite some work, it would be slow, yield larger files, 
it is not efficient.
