### ISSUE TITLE
About legacy release

### ISSUE THREAD

**Issue by shinaoka** [TRIQS/triqs#597]
Hi,

TRIQS 1.4.x is a legacy release since TRIQS 2.0 has been released.
What is your policy about supporting legacy releases?

I still see minor bugs in TRIQS 1.4.2.
Do you accept any bug fixes from us on TRIQS 1.4.x?

Although we're going to to TRIQS 2.0 at some point,
it would be nice if we have a TRIQS 1.4.x branch in GitHub for a while.

**Comment by mferrero** [comment]
Hi. All our developments will be done on the latest release. If we find bugs that would affect an earlier version of TRIQS, such as 1.4, we will not port them systematically. However, if you are using 1.4 and ask us to include a bug fix that you really need, we can do that, at least for a couple of months so that you have enough time to switch to 2.0.

**Comment by shinaoka** [comment]
Thank you for the reply.

Here is  a branch where I made  a minor modification to 1.4.2.
https://github.com/shinaoka/triqs/tree/1.4.x

I could make a PR if you make a branch for 1.4.x in the official TRIQS repository.

**Comment by mferrero** [comment]
Hi! I added a 1.4.x branch so that you can make the pull request.

**Comment by shinaoka** [comment]
Thank you. I made a PR. We will make PR's if we find any problems in 1.4.x.
