### ISSUE TITLE
Tail of noisy data does not fulfill GF properties 

### ISSUE THREAD

**Issue by mzingl** [TRIQS/triqs#607]
```
from pytriqs.gf import *
import numpy

# complex Hamiltonian
H = np.ones((2,2)) + 1j*np.ones((2,2))
H = 0.5*(H + np.transpose(np.conj(H)))

# GF iw
g = GfImFreq(indices = [0,1], beta = 50, n_points = 1000)
gt = GfImTime(indices = [0], beta = 50)

g << inverse( iOmega_n + H )

# Test if G_ij(iw) = G*_ij(-iw) (should be exactly 0)
print g.data[0,:,:] - np.transpose(np.conj(g.data[-1,:,:]))

# Look at the effect of random noise - matrix properties not fulfilled at all!
gt << InverseFourier(g)
gt.data[:,:,:] = gt.data[:,:,:] + 1e-3 * np.reshape(np.random.rand(np.size(gt.data)), np.shape(gt.data)) 
g << Fourier(gt)
print g.data[0,:,:] - np.transpose(np.conj(g.data[-1,:,:]))
```

In principle for a GF   G_ab(iw) = G*_ba(-iw)   is valid.
I understand that already the noise breaks this restriction. However, in practice we deal with noisy data, thus this has to be corrected in some way.
My opinion is: No matter how noisy the data is, the tail should always fulfill the properties of GFs.

Another aspect was brought to my attention by Gernot:
It is not sufficient (not working well) if one averages only over the parameters of the positive and negative fit. One needs to directly constrain the fit itself!

**Comment by mzingl** [comment]
I was a bit too fast here. The stated property is only valid for real G(tau). 
So probably, imposing this constrain is only possible on the cthyb side, where the fit is
performed, and not directly in the library.

**Comment by gkraberger** [comment]
Why is this only valid for real G(tau)? It should be valid for all Hermitian G(tau) (or A(w)).
![screenshot_20180712_100249](https://user-images.githubusercontent.com/16017581/42620389-1f1c02f6-85bb-11e8-835f-1aa5c9028b8e.png)

**Comment by Wentzell** [comment]
@gkraberger I think we should still enforce this generic property for any QMC Green function result. Do you agree?

**Comment by mzingl** [comment]
I'm sorry, I corrected to code and the text. I forgot the transpose in the text. 
So this means G_ab(iw) = G*_ba(-iw) follows from the hermiticity of A. Thanks Gernot!
Shouldn't this be imposed by the tailfit procedure no matter how the GF data looks like?

**Comment by gkraberger** [comment]
@Wentzell, I can only think of two reasons against enforcing it:
1. depending on how this would be enforced, if it is e.g. just symmetrized in the end, you might not be able to detect an error that you could find when the property is violated. If you can incorporate it into the algorithm somehow, so that it can never possibly be violated, that would not be a problem, of course.
2. Would the QMC work for non-Hermitian A(w) and is there any strange theory that features non-Hermitian A(w) that someone might want to do (maybe something with dissipation or non-orthonormal bases, but I did never really think about any of that)?

For all uses of TRIQS and CTHYB that I know of, enforcing it should be fine.

**Comment by HugoStrand** [comment]
@Wentzell I think this should be enforced as a constraint in _every_ tail fit, also the ones used when doing Fourier transforms.

**Comment by gkraberger** [comment]
I still think that there's something wrong with the tail_fit implementation for complex Gf in TRIQS 2.0.
In the case where we know the tail exactly because we have a non-interacting Green's function with just a Hamiltonian, we get deviations from the exact answer 1 order of magnitude higher than in TRIQS 1.4.

```
import numpy as np
try:
    from pytriqs.gf import *
    GfImFreq
    t2 = True
except:
    from pytriqs.gf.local import *
    t2 = False

G_iw =  GfImFreq(indices = [0,1], beta = 50.0, n_points = 2000)
H = np.array([[1.0, 0.1j],[-0.1j, 2.0]])
G_iw << inverse(iOmega_n - H)
if t2:
    from pytriqs.gf.gf_fnt import *
    tail, error = G_iw.fit_tail_on_window(n_min=1000, n_max=1999, known_moments=np.zeros((0,2,2), dtype=np.complex_), n_tail_max=4000, expansion_order=8)
else:
    G_iw.fit_tail(known_moments=TailGf(2,2,0,0), max_moment=8, pos_n_min=1000, pos_n_max=1999, neg_n_min=-2000, neg_n_max=-1001, replace_by_fit=False)
    tail = G_iw.tail.data[1:]
for n in range(8):
    theoretical = np.linalg.matrix_power(H, n)
    fitted = tail[n + 1]
    print theoretical
    print fitted
    print np.max(np.abs(theoretical-fitted))
    print
```

I tried to perform the tail fit with the same parameters in both cases, I hope I succeeded in doing so. If not, please teach me...

**Comment by Wentzell** [comment]
We do now provide the functionality to enforce the property ```G_ab(iw) = G*_ba(-iw)``` during the tail-fit.
This is achieved with the  ```fit_hermitian_tail``` function. Cf. https://triqs.github.io/triqs/unstable/reference/gfs/c++/tail.html
