### ISSUE TITLE
Stop calling std::complex<double> default constructor on allocation of gf<...>

### ISSUE THREAD

**Issue by HugoStrand** [TRIQS/triqs#625]
Dear all,

I am working with large Green's functions in frequency and momentum and the allocation of the Green's function object starts to take a substantial part of the computational time. The issue is that `triqs::arrays:array` calls the default constructor of it's element type, which for `std::complex<>` sets the value to zero. 

Could you please add a special case in the allocator of `triqs::arrays::array` that uses `malloc` or similar?

Best regards,
Hugo

**Comment by parcollet** [comment]
It is called because it is the default constructor.
It is easy to change, but breaks backward compatibility !

At minimum, the new NDA class will adopt this change.
In the current code, how to proceed ?
@wentzell : to put you in the loop.

**Comment by HugoStrand** [comment]
There is a solution that will not break backwards compatibility.

Writing a separate initialization for arrays with complex data type that does not call the default constructor of `std::complex` but rather just zero fills the whole memory area using a posix `memset` call.

Can we do that?

**Comment by Wentzell** [comment]
The default constructor of `array<std::complex<double>,N>` is in fact optimized to a single `memset` call by the compiler.
The proper solution to reach numpy-level allocation speeds was to use [`calloc`](https://en.cppreference.com/w/cpp/memory/c/calloc) instead.
This reason is explained in length [here](https://stackoverflow.com/questions/2688466/why-mallocmemset-is-slower-than-calloc). This has been resolved in fbe89489c24f46215d8e5e6c5376ba1e8fdda03a
