### ISSUE TITLE
Long builds and large RAM footprint. Split gf_fnt.py in pieces?

### ISSUE THREAD

**Issue by HugoStrand** [TRIQS/triqs#635]
Dear all,

The last six months the build time and memory requirement to build the c++ wrapper for `gf_fnt.py` has increased drastically. On some of my cluster machines I can no longer build triqs on the login node since that particular compilations uses too much RAM and gets killed. 

I would suggest that we split the methods wrapped into several smaller sub module files. This will enable parallel builds and reduce the memory footprint somewhat.

Is there some argument against this?

Best, Hugo

**Comment by parcollet** [comment]
Yes, we can do this, no issue.

**Comment by HugoStrand** [comment]
Good. Who, when, and how?

**Comment by patryk-kubiczek** [comment]
I also had problems with building gf_fnt target. The build would not even start. I was able to track the commit which made this target unable to compile, namely: https://github.com/TRIQS/triqs/commit/c6759f438272a62a2f4a7ad27e1983be95702929 . I had to go one commit back in order to be able to use TRIQS 2.0 on my machine.

**Comment by parcollet** [comment]
Move to cpp2py issue.

**Comment by Wentzell** [comment]
> Move to cpp2py issue.

Indeed. As discussed this problem should be resolved at the level of cpp2py.
I have opened a corresponding [issue](https://github.com/TRIQS/cpp2py/issues/22) for cpp2py.
