### ISSUE TITLE
[cmake] Suggestion: Place 'gtest' target into a namespace

### ISSUE THREAD

**Issue by krivenko** [TRIQS/triqs#654]
Hello,

I am trying to write a small header-only library (a C++ wrapper around ARPACK) that would be usable in conjunction with a few array/matrix algebra libraries. One of those libraries is going to be `triqs::arrays`.

There are going to be a number of unit tests that will optionally be built depending on the availability of respective matrix libraries. All those tests will be linked to `libgtest.so`, downloaded and built alongside the tests themselves.
Now the problem is that `find_package(TRIQS)` imports a target called `gtest`, and it conflicts with a similar target created by CMake scripts of Google Test. I could not find a way to 'undefine' imported targets, so I guess the only viable solution would be to place `gtest` into a namespace (`triqs::gtest`) and therefore make it possible for applications to use their own copies of Google Test.

Igor

**Comment by parcollet** [comment]
Yes, we agree , we have a similar problem.
Assigned to Nils.

**Comment by Wentzell** [comment]
@parcollet This would require the according update of all c++ applications.
It seems to be a bit tricky to make an alias ```triqs::gtest -> gtest``` in the application cmake if necessary in order to keep backward compatibility against previous triqs commits...

Note that we are currently considering to remove the triqs gtest target completely and have each c++ application pull in the gtest dependency (with e.g. ExternalProject_add, conan).

Maybe instead of going through the intermediate solution of a triqs::gtest target we should come to a conclusion if we want to even keep the exported gtest target at all.

**Comment by krivenko** [comment]
@Wentzell FYI, I somehow got around the problem by switching to [Catch2](https://github.com/catchorg/Catch2) test framework.

**Comment by Wentzell** [comment]
In commit 906a966b I have moved the gtest target into the triqs:: namespace.
I have however kept a global alias for now. The alias will be removed once applications are ported.

**Comment by Wentzell** [comment]
This issue is resolved in triqs/unstable. In fact we are no longer provide a gtest installation together with triqs. Instead each cmake project should compile and link its own version of gtest as recommended by google. This is for example achieved in [app4triqs](https://github.com/triqs/app4triqs), see [here](https://github.com/TRIQS/app4triqs/blob/unstable/test/c%2B%2B/CMakeLists.txt)
