### ISSUE TITLE
Documentation-provided install.sh currently broken

### ISSUE THREAD

**Issue by mueslo** [TRIQS/triqs#680]
Since `install.sh` does not pin the commit which is used, the latest version of both TRIQS and CPP2PY is pulled. However, they are currently incompatible due to HDF5 stuff being pulled out of CPP2PY.

I personally fixed it by adding the following line after the clone of cpp2py:

    cd cpp2py.src; git checkout 9fbee55662ae21013894bdb5c309705d0affd9e5; cd ..

but there should probably a single location where the appropriate git revision of cpp2py is specified.

**Comment by Wentzell** [comment]
Hey,

This problem is already resolved on the current triqs/unstable branch and will soon be merged into master.

We are now building and installing a particular cpp2py version together with triqs.
The cpp2py project is incorporated using the `git subtree` command.
See commits 774f7b8c9b9a5a9eca6685a12b717fec93482f8d and 5a3df453985544d6825503065e5c3b2b3bdd4690.

Note however that cpp2py remains an independent project and development of the tool will continue at
[github.com/triqs/cpp2py](https://github.com/triqs/cpp2py)

**Comment by Wentzell** [comment]
The changes are now available also on triqs/master
