### ISSUE TITLE
Definition of "density" for imaginary-time Green's functions

### ISSUE THREAD

**Issue by shinaoka** [TRIQS/triqs#696]
Hi, 

If I understand the code correctly,
density() seems to return the matrix D_{ij} = -G_{ij}(beta + 0^-) = <c_j^\dagger c_i>.
It was a bit surprising to me since the notation of D_{ij} = <c_i^\dagger c_j> looks more natural.
The transpose does matter for complex G(tau).
I did not find any document on the definition of "density" in the doc.
Is this intended behavior?

https://github.com/TRIQS/triqs/blob/master/triqs/gfs/functions/density.cpp#L201

**Comment by shinaoka** [comment]
@Wentzell @parcollet @aichhorn 
This may matter in computing noncolinear magnetic structures.

dft_tools may not handle this issue correctly.
https://github.com/TRIQS/dft_tools/blob/master/python/sumk_dft.py#L1290

**Comment by Wentzell** [comment]
@mzingl Could you have a quick look?

**Comment by mzingl** [comment]
In dft_tool density(), i.e. density_matrix() which also calls density(), is used in analyse_block_structure,  trans_basis and density_correction. I'm not sure about the density_correction for charge self-consistent calculations, but otherwise I don't see where this definition of the density is problematic. 
@aichhorn Can you have a look at this?

**Comment by Wentzell** [comment]
This was corrected in e7f979e
