### ISSUE TITLE
Filling a block green function with placeholder does not work properly

### ISSUE THREAD

**Issue by CorentinB78** [TRIQS/triqs#810]
### Description

Using a placeholder to fill a block real frequency green function do not result on the expected result. The block green function is filled, but not with the correct values. 

### Steps to Reproduce

```
#include <iostream>
#include <triqs/gfs.hpp>

using namespace triqs::gfs;
using triqs::clef::placeholder;

int main() {
  placeholder<0> w_;
  auto freq_mesh = gf_mesh<refreq>({-10., 10., 200});
  gf<refreq, scalar_valued> g(freq_mesh);
  auto G = make_block_gf({"up", "down"}, {g, g});

  G(w_) << w_ + 0.5 - 0.1i;

  std::cout << G[0](1.0) << std::endl;
  std::cout << G[0](2.5) << std::endl;

  return 0;
}
```

Same problem appeared with matrix valued green function, or using `G[w_]`.

**Expected behavior:**

```
(1.5,-0.1)
(3.0,-0.1)
```

**Actual output:**

```
(0.5,-0.1)
(0.5,-0.1)
```

### Versions

Triqs 3.0.x (bfdf5324)
Fedora 32

**Comment by Wentzell** [comment]
Dear @CorentinB78,

As discussed this behavior is expected because the placeholder will loop over the block index, which is always the first argument to a `block_gf`, and not the frequency.

```c++
G(bl_) << bl_ + 0.5 - 0.1i;
```

This expression will initialize each block of the Green function to the same constant for all frequency values.

If you want to initialize all blocks to the expression in your example you will need to write

```c++
placeholder<0> w_;
placeholder<1> bl_;

...
G[bl_](w_) << w_ + 0.5 - 0.1i;
```
