### ISSUE TITLE
TRIQS on GPU.

### ISSUE THREAD

**Issue by sujanbharadwaj** [TRIQS/triqs#929]
Dear TRIQS Team, 
I would like to know whether TRIQS-cthyb supports GPU.

**Comment by the-hampel** [comment]
Hi @sujanbharadwaj ,
as of now we do not support GPUs for cthyb (or any other solver). We started to bring some GPU awareness to the base array class in triqs/NDA to allow developers to utilize GPUs. Development is in its early stages but we will continue developing features to enable GPU support in the future.

**Comment by sujanbharadwaj** [comment]
Dear @the-hampel 
Thanks for the reply. It would be very helpful if we could run TRIQS-cthyb on GPUs. I am very happy to hear that the TRIQS Community is working towards this development.

**Comment by the-hampel** [comment]
Since you are specifically asking about cthyb I would like to make some comments. To my knowledge GPU support has only be implemented in this paper: https://arxiv.org/abs/2010.08482 for performing the determinant updates. It is shown that this only provides some speedup in impurity problems with more than 5 orbitals, e.g. f-shells. So depending on the problem you would like solve it is not even that clear how a GPU implementation should work. This is partially why we did not pursue GPU support yet.

**Comment by sujanbharadwaj** [comment]
Hi @the-hampel 
Thanks for the information.

**Comment by 70akaline** [comment]
> Since you are specifically asking about cthyb I would like to make some comments. To my knowledge GPU support has only be implemented in this paper: https://arxiv.org/abs/2010.08482 for performing the determinant updates. It is shown that this only provides some speedup in impurity problems with more than 5 orbitals, e.g. f-shells. So depending on the problem you would like solve it is not even that clear how a GPU implementation should work. This is partially why we did not pursue GPU support yet.

Hi, Alex, have you read this paper before about accelerating (by GPU) CT-AUX?
https://ieeexplore.ieee.org/abstract/document/8891643
https://www.sciencedirect.com/science/article/pii/S0010465519300086

I guess somehow, DCA++ now also has similar algorithm for CT-SEG/CT-INT:
https://github.com/CompFUSE/DCA

Perhaps, those strategy could be used for matrix CT-HYB as well

**Comment by Wentzell** [comment]
Thank you @70akaline for bringing up these other efforts to use GPUs for impurity solver acceleration.
We will consider these strategies in our development efforts.
